import frappe
from frappe.model.document import Document

@frappe.whitelist()
# Fuction for passing data from patient draft to  patient
def before_submit(
    first_name,sur_name,date_of_enrolment,zone,address,mobile_number1,mobile_number,first_name1,middle_name=None,
    salutation=None,
    locality=None,
    telephone_number=None,
    email=None,
    date_of_birth=None,
    age=None,
    gender=None,
    number_of_family_members_in_the_same_house=None,
    primary_language=None,
    pan_no=None,
    aadhar_no=None,
    connection_to_patient=None,
    middle_name1=None,
    sur_name1=None,
    locality1=None,
    telephone_number1=None,
    email1=None,
    connection_to_patient1=None,
    fst_name2=None,
    mdl_name2=None,
    srname2=None,
    locality2=None,
    mobile_no2=None,
    emal2=None,
    con=None,
    first_name7=None,
    middle7=None,
    su7=None,
    locality7=None,
    mb7=None,
    tn7=None,
    email7=None,
    first_name2=None,
    middle_name2=None,
    sur_name2=None,
    mobile_number2=None,
    telephone_number2=None,
    email2=None,
    first_name3=None,
    middle_name3=None,
    sur_name3=None,
    mobile_number3=None,
    telephone_number3=None,
    email3=None,
    first_name4=None,
    middle_name4=None,
    sur_name4=None,
    mobile_number4=None,
    telephone_number4=None,
    email4=None,
    first_name6=None,
    mid6=None,
    sur6=None,
    mb6=None,
    tn6=None,
    email6=None,
    priority=None,
    marital_status=None,
    classification=None,
    employment=None,
    education=None,
    address1=None,
    adrs2=None,
    ad7=None,
    address2=None,
    address4=None,
    ad6=None,
    address3=None,
    type_of_referral=None,
    telephone_no2=None,
    pincode=None,
    pin_code1=None,
    pin_code2=None,
	pin_code3=None,
    pin_code4=None,
    pin_code5=None,
    pin_code6=None,
    pin_code7=None
    ):
    pat_doc = frappe.get_doc({
        'doctype': 'Patient',
        'first_name': first_name,
        'middle_name': middle_name,
        'sur_name': sur_name,
        'date_of_enrolment': date_of_enrolment,
        'zone': zone,
        'address': address,
        'mobile_number': mobile_number,
        'first_name1': first_name1,
        'mobile_number1': mobile_number1,
        'salutation': salutation,
        'locality': locality,
        'telephone_number': telephone_number,
		'email':email,
		'date_of_birth':date_of_birth,
		'age':age,
		'gender':gender,
		'number_of_family_members_in_the_same_house':number_of_family_members_in_the_same_house,
		'primary_language':primary_language,
		'pan_no':pan_no,
		'aadhar_no':aadhar_no,
		'telephone_no2':telephone_no2,
		'connection_to_patient':connection_to_patient,
		'middle_name1':middle_name1,
		'sur_name1':sur_name1,
		'locality1':locality1,
		'telephone_number1':telephone_number1,
		'email1':email1,
		'connection_to_patient1':connection_to_patient1,
		'type_of_referral':type_of_referral,
		'fst_name2':fst_name2,
		'mdl_name2':mdl_name2,
		'srname2':srname2,
		'locality2':locality2,
		'mobile_no2':mobile_no2,
		'emal2':emal2,
		'con':con,
		'first_name7':first_name7,
		'middle7':middle7,
		'su7':su7,
		'locality7':locality7,
		'mb7':mb7,
		'tn7':tn7,
		'email7':email7,
		'first_name2':first_name2,
		'middle_name2':middle_name2,
		'sur_name2':sur_name2,
		'mobile_number2':mobile_number2,
		'telephone_number2':telephone_number2,
		'email2':email2,
		'first_name3':first_name3,
		'middle_name3':middle_name3,
		'sur_name3':sur_name3,
		'mobile_number3':mobile_number3,
		'telephone_number3':telephone_number3,
		'email3':email3,
		'first_name4':first_name4,
		'middle_name4':middle_name4,
		'sur_name4':sur_name4,
		'mobile_number4':mobile_number4,
		'telephone_number4':telephone_number4,
		'email4':email4,
		'first_name6':first_name6,
		'mid6':mid6,
		'sur6':sur6,
		'mb6':mb6,
		'tn6':tn6,
		'email6':email6,
		'priority':priority,
		'marital_status':marital_status,
		'classification':classification,
		'employment':employment,
		'education':education,
		'address1':address1,
		'adrs2':adrs2,
		'ad7':ad7,
		'address2':address2,
		'address3':address3,
		'address4':address4,
		'ad6':ad6,
        'pincode':pincode,
        'pin_code1':pin_code1,
        'pin_code2':pin_code2,
		'pin_code3':pin_code3,
        'pin_code4':pin_code4,
        'pin_code5':pin_code5,
        'pin_code6':pin_code6,
        'pin_code7':pin_code7
        })

    print(pat_doc)
	
    pat_doc.insert()

    pat_doc.save()
